---
name: CI/CD

on:
  pull_request: {}
  push: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run all
    - name: Update latest tag when pushing to main
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        git tag -f latest
        git push -f origin latest
    - name: Publish myself
      if: ${{ github.event_name == 'push' }}
      uses: ./
      with:
        replace: latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git tag -f ghatest
    - run: git push -f origin ghatest
    - name: generate a test release
      uses: ./
      with:
        ref: 'refs/tags/ghatest'
        replace: ghatest
        files: |
          README.md
          src/main.ts
    - name: remove it again
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: ghatest
        delete_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
